### ISSUE TITLE
[feat] 추가 Q9View

### ISSUE THREAD

**Issue by geee3** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#24]
## ✍️ Description
Question 07 표정 뷰 구현

## ⚒️ Todo
- [x] 모달 뷰
- [x] Drawing Manager
- [x] Drawing View
- [x] 그림 저장기능 구현

## ⚙️ ETC
그림을 JSON에 어떻게 저장할지 생각해 보아요

**Comment by abovocado** [comment]
메인에 추가 완료

**Comment by abovocado** [comment]
메인에 추가 완료
